=== och575411878/algorithm/字符串/src/测试xml/student1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="myschema1"
        elementFormDefault="qualified"
>
    <!--定义persons复杂元素-->
    <xs:element name="persons">
        <xs:complexType>
            <sequence>
                <!--定义person复杂元素-->
                <element name="student">
                    <complexType>
                        <sequence>
                            <!--定义name和age简单元素-->
                            <element name="name" type="string"/>
                            <element name="score" type="string"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== och575411878/algorithm/字符串/src/测试xml/a.xml
<?xml version="1.0" encoding="UTF-8" ?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:student1 = "myschema1"
xmlns:student2 = "myschema2"
xsi:schemaLocation="http://example.com/student1 student1.xsd
                             http://example.com/student2 student2.xsd"
>
    <student1:persons>
        <student1:student>
            <student1:name>aa</student1:name>
            <student1:score>bb</student1:score>
        </student1:student>
    </student1:persons>

    <student2:persons>
        <student2:student>
            <student2:name>aa</student2:name>
            <student2:id>aa</student2:id>
        </student2:student>
    </student2:persons>
</persons>
